### ISSUE TITLE
Dynamic Roles

### ISSUE THREAD

**Issue by sachalifs** [DemocracyOS/NetID#13]
Roles and actions are now static, defined in the `security.yml` file.
They should be stored in the database and the admin should be able to assign each action individually to any user.

**Comment by cristiandouce** [comment]
:+1: 

Check also how to load a few predefined roles via fixtures. I know there is a Doctrine fixtures bundle that could manage that.

**Comment by sachalifs** [comment]
Solved in c37db612c7e43445d702d48c9133b7cf6e39f251
