### ISSUE TITLE
Basic oAuth API

### ISSUE THREAD

**Issue by gvilarino** [DemocracyOS/NetID#2]
Provide a basic oAuth API (app keys and secrets) and try it out with curl.

Then create a set for @DemocracyOS and get them to @cristiandouce

**Comment by sachalifs** [comment]
Merged to master. /users URL is protected under OAuth protocol. 
To get an access token, do a POST Request to /oauth/v2/token?client_id=CLIENT_ID&client_secret=CLIENT_SECRET&grant_type=client_credentials

An example with cURL would be:
curl -X POST -d "client_id=CLIENT_ID&client_secret=CLIENT_SECRET&grant_type=client_credentials" http://netid.dev/app_dev.php/oauth/v2/token

**Comment by cristiandouce** [comment]
:hand:
