### ISSUE TITLE
Users

### ISSUE THREAD

**Issue by gvilarino** [DemocracyOS/NetID#3]
We need to persist users in order to manage their validation status. For that we'll need a model.

V1, users should support:
- name: complete first, second, etc. names
- lastName: complete surnames
- birthDate: date of birth (use ISO date formatting)
- legalId: legal ID the user used for registering (e.g.: DNI number in Argentina).
- discrict: legal distric where the user is registered for voting.
- apps: collection of tuples with:
  - appId: id of the app the user is registered to
  - foriegnId: id of the user in the third-party app

For instance, the JSON for a user of @DemocracyOS should look like:

``` json
{
  name: "Carlos Alberto",
  lastName: "Toma y Araujo",
  birthDate: "1997-07-16",
  legalID: {
    name: "DNI",
    number: "29455231"
  },
  district: "Ciudad Autónoma de Buenos Aires",
  apps: {
    appId: "democracy-os",
    foreignId: "#12f2931ffa91"
  }
}
```

**Comment by sachalifs** [comment]
User model finished.

Accented characters are json_encoded like this, e.g.: _"Ciudad Autónoma de Buenos Aires"_ becomes _"Ciudad Aut\u00f3noma de Buenos Aires"_
