### ISSUE TITLE
[NetID] - 500 Error when pressing "Show"

### ISSUE THREAD

**Issue by cristiandouce** [DemocracyOS/NetID#39]
kudos @bastianhell 

Steps to reproduce

1- Login on NetId as root
2- Select Identity from Content dropdown
3- Click Show action on any user

Result: 500 Error.

Original: DemocracyOS/app#260

**Comment by gvilarino** [comment]
@bastianhell i forgot to give you permissions on this repo. Sorry about that :dancers:
